<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="66" errors="2" failures="1" skip="1"><testcase classname="integration.test_afterbuy.TestAfterbuy" name="test_check_login" time="0.413"></testcase><testcase classname="integration.test_afterbuy.TestAfterbuy" name="test_create_item" time="0.004"></testcase><testcase classname="integration.test_afterbuy.TestAfterbuy" name="test_create_new_user" time="0.063"></testcase><testcase classname="integration.test_afterbuy.TestAfterbuy" name="test_product_details" time="0.005"></testcase><testcase classname="integration.test_api.AfterBuyIntegrationTests" name="test_brands" time="0.286"></testcase><testcase classname="integration.test_api.AfterBuyIntegrationTests" name="test_products" time="0.059"></testcase><testcase classname="integration.test_api.AfterBuyIntegrationTests" name="test_users" time="0.070"></testcase><testcase classname="integration.test_celery.CeleryTestCaseBase" name="test_delay_message" time="0.042"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_asc_feed" time="2.406"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_authentication" time="2.139"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_coupon_redamption_feed" time="6.088"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_coupon_status_on_dispatch_feed" time="0.000"><skipped type="unittest.case.SkipTest" message="Skipping Adding this functionality in future"><![CDATA[SkipTest: Skipping Adding this functionality in future
]]></skipped></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_coupon_status_without_ucn" time="2.004"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_partial_fail" time="2.382"><failure type="exceptions.AssertionError" message="200 != 500&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;gladminds: INFO: New dealer Registration with id - GMDEALER002&#10;gladminds: INFO: [Exception: new_ registration]: Group matching query does not exist.&#10;gladminds: INFO: [Exception: new_ registration]: User matching query does not exist.&#10;gladminds: INFO: dealer GMDEALER002 registered successfully&#10;gladminds: INFO: New SA Registration with id - GMDEALER001SA02&#10;gladminds: INFO: [Exception: new_ registration]: Group matching query does not exist.&#10;gladminds: INFO: [Exception: new_ registration]: User matching query does not exist.&#10;gladminds: INFO: SA GMDEALER001SA02 registered successfully&#10;gladminds: INFO: New dealer Registration with id - GMDEALER001&#10;gladminds: INFO: [Exception: new_ registration]: User matching query does not exist.&#10;gladminds: INFO: dealer GMDEALER001 registered successfully&#10;gladminds: ERROR: [Exception: DealerAndServiceAdvisorFeed_sa]: NOT NULL constraint failed: aftersell_serviceadvisor.service_advisor_id&#10;boto: DEBUG: Using access key provided by client.&#10;boto: DEBUG: Using secret key provided by client.&#10;boto: DEBUG: path=/&#10;boto: DEBUG: auth_path=/gladminds/&#10;boto: DEBUG: path=/?max-keys=0&#10;boto: DEBUG: auth_path=/gladminds/?max-keys=0&#10;boto: DEBUG: Method: GET&#10;boto: DEBUG: Path: /?max-keys=0&#10;boto: DEBUG: Data: &#10;boto: DEBUG: Headers: {}&#10;boto: DEBUG: Host: gladminds.s3.amazonaws.com&#10;boto: DEBUG: Port: 443&#10;boto: DEBUG: Params: {}&#10;boto: DEBUG: establishing HTTPS connection: host=gladminds.s3.amazonaws.com, kwargs={'port': 443, 'timeout': 70}&#10;boto: DEBUG: Token: None&#10;boto: DEBUG: StringToSign:&#10;GET&#10;&#10;&#10;Fri, 27 Jun 2014 11:41:30 GMT&#10;/gladminds/&#10;boto: DEBUG: Signature:&#10;AWS AKIAIL7IDCSTNCG2R6JA:CWZC8Uv3R23tmLCbQ5fmY5pCEP0=&#10;boto: DEBUG: &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&#10;&lt;ListBucketResult xmlns=&quot;http://s3.amazonaws.com/doc/2006-03-01/&quot;&gt;&lt;Name&gt;gladminds&lt;/Name&gt;&lt;Prefix&gt;&lt;/Prefix&gt;&lt;Marker&gt;&lt;/Marker&gt;&lt;MaxKeys&gt;0&lt;/MaxKeys&gt;&lt;IsTruncated&gt;false&lt;/IsTruncated&gt;&lt;/ListBucketResult&gt;&#10;boto: DEBUG: path=/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log&#10;boto: DEBUG: auth_path=/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log&#10;boto: DEBUG: Method: PUT&#10;boto: DEBUG: Path: /aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log&#10;boto: DEBUG: Data: &#10;boto: DEBUG: Headers: {'Content-Length': '2', 'Content-MD5': 'mZFLkyvTelC5g8XnyQrpOw==', 'Content-Type': 'text/plain', 'Expect': '100-Continue', 'User-Agent': 'Boto/2.21.2 Python/2.7.6 Linux/3.13.0-30-generic'}&#10;boto: DEBUG: Host: gladminds.s3.amazonaws.com&#10;boto: DEBUG: Port: 443&#10;boto: DEBUG: Params: {}&#10;boto: DEBUG: Token: None&#10;boto: DEBUG: StringToSign:&#10;PUT&#10;mZFLkyvTelC5g8XnyQrpOw==&#10;text/plain&#10;Fri, 27 Jun 2014 11:41:31 GMT&#10;/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log&#10;boto: DEBUG: Signature:&#10;AWS AKIAIL7IDCSTNCG2R6JA:T9+hBED9jpRsrG/sXdouehLVVJ8=&#10;boto: DEBUG: path=/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log&#10;boto: DEBUG: auth_path=/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log&#10;boto: DEBUG: path=/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log?acl&#10;boto: DEBUG: auth_path=/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log?acl&#10;boto: DEBUG: Method: PUT&#10;boto: DEBUG: Path: /aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log?acl&#10;boto: DEBUG: Data: &#10;boto: DEBUG: Headers: {'x-amz-acl': 'public-read'}&#10;boto: DEBUG: Host: gladminds.s3.amazonaws.com&#10;boto: DEBUG: Port: 443&#10;boto: DEBUG: Params: {}&#10;boto: DEBUG: Token: None&#10;boto: DEBUG: StringToSign:&#10;PUT&#10;&#10;&#10;Fri, 27 Jun 2014 11:41:32 GMT&#10;x-amz-acl:public-read&#10;/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log?acl&#10;boto: DEBUG: Signature:&#10;AWS AKIAIL7IDCSTNCG2R6JA:0t8yTzn7JJk1D1VET62NBfPL4gk=&#10;gladminds: INFO: Feed File Failure Uploaded: aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log has been uploaded&#10;py.warnings: WARNING: /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField DataFeedLog.timestamp received a naive datetime (2014-06-27 17:11:32.709671) while time zone support is active.&#10;  RuntimeWarning)&#10;&#10;spyne.application: ERROR: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.&#10;Traceback (most recent call last):&#10;  File &quot;/home/naureen/workspace/gladminds/eggs/spyne-2.10.10-py2.7.egg/spyne/application.py&quot;, line 126, in process_request&#10;    ctx.out_object = self.call_wrapper(ctx)&#10;  File &quot;/home/naureen/workspace/gladminds/eggs/spyne-2.10.10-py2.7.egg/spyne/application.py&quot;, line 167, in call_wrapper&#10;    return ctx.service_class.call_wrapper(ctx)&#10;  File &quot;/home/naureen/workspace/gladminds/eggs/spyne-2.10.10-py2.7.egg/spyne/service.py&quot;, line 210, in call_wrapper&#10;    return ctx.function(*ctx.in_object)&#10;  File &quot;/home/naureen/workspace/gladminds/src/gladminds/webservice.py&quot;, line 250, in postDealer&#10;    feed_remark.save_to_feed_log()&#10;  File &quot;/home/naureen/workspace/gladminds/src/gladminds/aftersell/feed_log_remark.py&quot;, line 45, in save_to_feed_log&#10;    action=self.action, remarks=remarks, file_location=path)&#10;  File &quot;/home/naureen/workspace/gladminds/src/gladminds/audit.py&quot;, line 27, in feed_log&#10;    data_feed_log.save()&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/models/base.py&quot;, line 545, in save&#10;    force_update=force_update, update_fields=update_fields)&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/models/base.py&quot;, line 573, in save_base&#10;    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/models/base.py&quot;, line 654, in _save_table&#10;    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/models/base.py&quot;, line 687, in _do_insert&#10;    using=using, raw=raw)&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py&quot;, line 232, in _insert&#10;    return insert_query(self.model, objs, fields, **kwargs)&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/models/query.py&quot;, line 1511, in insert_query&#10;    return query.get_compiler(using=using).execute_sql(return_id)&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py&quot;, line 903, in execute_sql&#10;    cursor.execute(sql, params)&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py&quot;, line 47, in execute&#10;    self.db.validate_no_broken_transaction()&#10;  File &quot;/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py&quot;, line 372, in validate_no_broken_transaction&#10;    &quot;An error occurred in the current transaction. You can't &quot;&#10;TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------"><![CDATA[  File "/usr/local/lib/python2.7/dist-packages/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/naureen/workspace/gladminds/tests/integration/test_feeds.py", line 188, in test_partial_fail
    self.assertEqual(200, response.status_code)
  File "/usr/local/lib/python2.7/dist-packages/unittest2/case.py", line 521, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python2.7/dist-packages/unittest2/case.py", line 514, in _baseAssertEqual
    raise self.failureException(msg)
'200 != 500\n-------------------- >> begin captured logging << --------------------\ngladminds: INFO: New dealer Registration with id - GMDEALER002\ngladminds: INFO: [Exception: new_ registration]: Group matching query does not exist.\ngladminds: INFO: [Exception: new_ registration]: User matching query does not exist.\ngladminds: INFO: dealer GMDEALER002 registered successfully\ngladminds: INFO: New SA Registration with id - GMDEALER001SA02\ngladminds: INFO: [Exception: new_ registration]: Group matching query does not exist.\ngladminds: INFO: [Exception: new_ registration]: User matching query does not exist.\ngladminds: INFO: SA GMDEALER001SA02 registered successfully\ngladminds: INFO: New dealer Registration with id - GMDEALER001\ngladminds: INFO: [Exception: new_ registration]: User matching query does not exist.\ngladminds: INFO: dealer GMDEALER001 registered successfully\ngladminds: ERROR: [Exception: DealerAndServiceAdvisorFeed_sa]: NOT NULL constraint failed: aftersell_serviceadvisor.service_advisor_id\nboto: DEBUG: Using access key provided by client.\nboto: DEBUG: Using secret key provided by client.\nboto: DEBUG: path=/\nboto: DEBUG: auth_path=/gladminds/\nboto: DEBUG: path=/?max-keys=0\nboto: DEBUG: auth_path=/gladminds/?max-keys=0\nboto: DEBUG: Method: GET\nboto: DEBUG: Path: /?max-keys=0\nboto: DEBUG: Data: \nboto: DEBUG: Headers: {}\nboto: DEBUG: Host: gladminds.s3.amazonaws.com\nboto: DEBUG: Port: 443\nboto: DEBUG: Params: {}\nboto: DEBUG: establishing HTTPS connection: host=gladminds.s3.amazonaws.com, kwargs={\'port\': 443, \'timeout\': 70}\nboto: DEBUG: Token: None\nboto: DEBUG: StringToSign:\nGET\n\n\nFri, 27 Jun 2014 11:41:30 GMT\n/gladminds/\nboto: DEBUG: Signature:\nAWS AKIAIL7IDCSTNCG2R6JA:CWZC8Uv3R23tmLCbQ5fmY5pCEP0=\nboto: DEBUG: <?xml version="1.0" encoding="UTF-8"?>\n<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>gladminds</Name><Prefix></Prefix><Marker></Marker><MaxKeys>0</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>\nboto: DEBUG: path=/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log\nboto: DEBUG: auth_path=/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log\nboto: DEBUG: Method: PUT\nboto: DEBUG: Path: /aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log\nboto: DEBUG: Data: \nboto: DEBUG: Headers: {\'Content-Length\': \'2\', \'Content-MD5\': \'mZFLkyvTelC5g8XnyQrpOw==\', \'Content-Type\': \'text/plain\', \'Expect\': \'100-Continue\', \'User-Agent\': \'Boto/2.21.2 Python/2.7.6 Linux/3.13.0-30-generic\'}\nboto: DEBUG: Host: gladminds.s3.amazonaws.com\nboto: DEBUG: Port: 443\nboto: DEBUG: Params: {}\nboto: DEBUG: Token: None\nboto: DEBUG: StringToSign:\nPUT\nmZFLkyvTelC5g8XnyQrpOw==\ntext/plain\nFri, 27 Jun 2014 11:41:31 GMT\n/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log\nboto: DEBUG: Signature:\nAWS AKIAIL7IDCSTNCG2R6JA:T9+hBED9jpRsrG/sXdouehLVVJ8=\nboto: DEBUG: path=/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log\nboto: DEBUG: auth_path=/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log\nboto: DEBUG: path=/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log?acl\nboto: DEBUG: auth_path=/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log?acl\nboto: DEBUG: Method: PUT\nboto: DEBUG: Path: /aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log?acl\nboto: DEBUG: Data: \nboto: DEBUG: Headers: {\'x-amz-acl\': \'public-read\'}\nboto: DEBUG: Host: gladminds.s3.amazonaws.com\nboto: DEBUG: Port: 443\nboto: DEBUG: Params: {}\nboto: DEBUG: Token: None\nboto: DEBUG: StringToSign:\nPUT\n\n\nFri, 27 Jun 2014 11:41:32 GMT\nx-amz-acl:public-read\n/gladminds/aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log?acl\nboto: DEBUG: Signature:\nAWS AKIAIL7IDCSTNCG2R6JA:0t8yTzn7JJk1D1VET62NBfPL4gk=\ngladminds: INFO: Feed File Failure Uploaded: aftersell/bajaj/feed-logs/dev/Dealer_Feed_aaf95bd9-55d9-4318-8c92-82fb42e89e38.log has been uploaded\npy.warnings: WARNING: /usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField DataFeedLog.timestamp received a naive datetime (2014-06-27 17:11:32.709671) while time zone support is active.\n  RuntimeWarning)\n\nspyne.application: ERROR: An error occurred in the current transaction. You can\'t execute queries until the end of the \'atomic\' block.\nTraceback (most recent call last):\n  File "/home/naureen/workspace/gladminds/eggs/spyne-2.10.10-py2.7.egg/spyne/application.py", line 126, in process_request\n    ctx.out_object = self.call_wrapper(ctx)\n  File "/home/naureen/workspace/gladminds/eggs/spyne-2.10.10-py2.7.egg/spyne/application.py", line 167, in call_wrapper\n    return ctx.service_class.call_wrapper(ctx)\n  File "/home/naureen/workspace/gladminds/eggs/spyne-2.10.10-py2.7.egg/spyne/service.py", line 210, in call_wrapper\n    return ctx.function(*ctx.in_object)\n  File "/home/naureen/workspace/gladminds/src/gladminds/webservice.py", line 250, in postDealer\n    feed_remark.save_to_feed_log()\n  File "/home/naureen/workspace/gladminds/src/gladminds/aftersell/feed_log_remark.py", line 45, in save_to_feed_log\n    action=self.action, remarks=remarks, file_location=path)\n  File "/home/naureen/workspace/gladminds/src/gladminds/audit.py", line 27, in feed_log\n    data_feed_log.save()\n  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save\n    force_update=force_update, update_fields=update_fields)\n  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 654, in _save_table\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\n  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 687, in _do_insert\n    using=using, raw=raw)\n  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 232, in _insert\n    return insert_query(self.model, objs, fields, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1511, in insert_query\n    return query.get_compiler(using=using).execute_sql(return_id)\n  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 903, in execute_sql\n    cursor.execute(sql, params)\n  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 47, in execute\n    self.db.validate_no_broken_transaction()\n  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 372, in validate_no_broken_transaction\n    "An error occurred in the current transaction. You can\'t "\nTransactionManagementError: An error occurred in the current transaction. You can\'t execute queries until the end of the \'atomic\' block.\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_product_dispatch" time="6.310"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_product_purchase" time="2.184"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_service_advisor_dealer_relationship" time="4.243"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_service_advisor_feed" time="2.594"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_service_advisor_phone_number_updation_logic" time="4.393"></testcase><testcase classname="integration.test_feeds.FeedsResourceTest" name="test_update_customer_number" time="6.009"></testcase><testcase classname="integration.test_home.TestHome" name="test_home" time="0.001"></testcase><testcase classname="integration.test_message.BrandData" name="test_get_all_brand" time="0.027"></testcase><testcase classname="integration.test_message.BrandData" name="test_get_all_products_of_a_brand" time="0.026"></testcase><testcase classname="integration.test_message.CouponCheckAndClosure" name="test_coupon_expiry" time="0.113"></testcase><testcase classname="integration.test_message.CouponCheckAndClosure" name="test_forward_logic_1" time="0.091"></testcase><testcase classname="integration.test_message.CouponCheckAndClosure" name="test_forward_logic_2" time="0.093"></testcase><testcase classname="integration.test_message.CouponCheckAndClosure" name="test_forward_logic_3" time="0.093"></testcase><testcase classname="integration.test_message.CouponCheckAndClosure" name="test_forward_logic_4" time="0.115"></testcase><testcase classname="integration.test_message.CouponCheckAndClosure" name="test_forward_logic_5" time="0.146"></testcase><testcase classname="integration.test_message.CouponCheckAndClosure" name="test_invalid_ucn_or_sap_id" time="0.087"></testcase><testcase classname="integration.test_message.CouponCheckAndClosure" name="test_simple_inprogress_from_unused" time="0.098"></testcase><testcase classname="integration.test_message.CustomerRegistrationTest" name="test_already_registered_customer" time="0.092"></testcase><testcase classname="integration.test_message.CustomerRegistrationTest" name="test_customer_registration" time="0.084"></testcase><testcase classname="integration.test_message.CustomerRegistrationTest" name="test_invalid_message" time="0.028"></testcase><testcase classname="integration.test_message.CustomerServiceTest" name="test_invalid_service" time="0.049"></testcase><testcase classname="integration.test_message.CustomerServiceTest" name="test_valid_service" time="0.026"></testcase><testcase classname="integration.test_registration.TestDealerRegistration" name="test_new_dealer" time="0.109"></testcase><testcase classname="integration.test_save_form.TestSaveFormRegistration" name="test_asc_registration" time="0.004"></testcase><testcase classname="integration.test_save_form.TestSaveFormRegistration" name="test_fail_registration_mail" time="0.003"></testcase><testcase classname="integration.test_sqs.TestSQSTasks" name="test_send_on_product_purchase" time="1.019"></testcase><testcase classname="unit.test_celery.TestCelery" name="test_send_sms" time="0.011"><error type="exceptions.AttributeError" message="'dict' object has no attribute 'successful'"><![CDATA[Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/unittest2/case.py", line 340, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 249, in inner
    return test_func(*args, **kwargs)
  File "/home/naureen/workspace/gladminds/tests/unit/test_celery.py", line 23, in test_send_sms
    self.assertTrue(result.successful())
AttributeError: 'dict' object has no attribute 'successful'
]]></error></testcase><testcase classname="unit.test_celery.TestCelery" name="test_send_sms_fail" time="0.008"><error type="exceptions.AttributeError" message="'dict' object has no attribute 'successful'"><![CDATA[Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/unittest2/case.py", line 340, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 249, in inner
    return test_func(*args, **kwargs)
  File "/home/naureen/workspace/gladminds/tests/unit/test_celery.py", line 29, in test_send_sms_fail
    self.assertFalse(result.successful())
AttributeError: 'dict' object has no attribute 'successful'
]]></error></testcase><testcase classname="unit.test_celery.TestCronjobs" name="test_expire_service_coupon" time="0.056"></testcase><testcase classname="unit.test_celery.TestCronjobs" name="test_get_data_feed_log_detail" time="0.041"></testcase><testcase classname="unit.test_celery.TestTasks" name="test_tasks" time="2.918"></testcase><testcase classname="unit.test_csvfeed.CSVFeedTest" name="test_brandproducttypefeed" time="0.007"></testcase><testcase classname="unit.test_csvfeed.CSVFeedTest" name="test_import_duplicate_feed" time="0.010"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_close_coupon" time="0.111"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_coupon_initiators" time="0.101"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_customer_service_detail" time="0.058"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_dispatch_gladminds" time="0.071"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_expire_or_close_less_kms_coupon" time="0.106"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_format_message" time="0.051"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_inprogress_coupon" time="0.115"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_is_valid_data" time="0.107"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_no_available_coupons" time="0.042"></testcase><testcase classname="unit.test_resource.GladmindsResourcesTest" name="test_register_customer" time="0.176"></testcase><testcase classname="unit.test_smsparser.SmsParserTest" name="test_invalid_keyword" time="0.015"></testcase><testcase classname="unit.test_smsparser.SmsParserTest" name="test_invalid_keyword_2" time="0.007"></testcase><testcase classname="unit.test_smsparser.SmsParserTest" name="test_invalid_message_format" time="0.013"></testcase><testcase classname="unit.test_smsparser.SmsParserTest" name="test_sms_parse" time="0.013"></testcase><testcase classname="unit.test_unit.TestAssertWorks" name="test_assert_equals" time="0.000"></testcase><testcase classname="unit.test_unit.TestAssertWorks" name="test_assert_true" time="0.000"></testcase><testcase classname="unit.test_unit.TestFeedLogWithRemark" name="test_remarks" time="6.043"></testcase><testcase classname="unit.test_unit.TestUtils" name="test_get_sa_list" time="0.068"></testcase><testcase classname="unit.test_unit.TestUtils" name="test_otp" time="0.068"></testcase></testsuite>